version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testegbvcaju
      MYSQL_DATABASE: teste_gbv_caju_db
      MYSQL_USER: caju
      MYSQL_PASSWORD: testegbvcaju
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: teste_gbv_caju
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      - SPRING_APPLICATION_NAME=teste
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/teste_gbv_caju_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      - SPRING_DATASOURCE_USERNAME=caju
      - SPRING_DATASOURCE_PASSWORD=testegbvcaju
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_TRANSACTION_COORDINATOR_CLASS=jdbc
      - SERVER_PORT=8080
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINTS_WEB_BASE_PATH=/actuator
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_COMPONENTS=always

    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
